server:
  port: 9999

spring:
  application:
    name: dynamic-thread-pool-test

thread:
  pool:
    config:
      enabled: true
      thread-pool-num: 2
      core-pool-size: 10
      max-pool-size: 20
      keep-alive-time: 60
      unit: SECONDS
      work-queue: LinkedBlockingQueue
      work-queue-capacity: 100
      rejected-execution-handler: CallerRunsPolicy

logging:
  level:
    root: info

app:
  config:
    api-version: v1
    cross-origin: "*"